In [2]:
import numpy as np
import pandas as pd


import warnings
warnings.filterwarnings('ignore')

from sklearn.metrics.pairwise import cosine_similarity

from sklearn.metrics import mean_squared_error


In [3]:
books = pd.read_csv('Books.csv')
users = pd.read_csv('Users.csv')
ratings = pd.read_csv('Ratings.csv')

In [4]:
ratings

User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

In [5]:
print(books.shape)
print(ratings.shape)
print(users.shape)

(271360, 8)
(1149780, 3)
(278858, 3)


In [6]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [7]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [8]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

Popularity Based 

In [9]:
ratings_with_name = ratings.merge(books,on='ISBN')

In [10]:
num_rating_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating':'num_ratings'},inplace=True)
num_rating_df

Book-Title  num_ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [11]:
avg_rating_df = ratings_with_name.groupby('Book-Title').mean(numeric_only=True)['Book-Rating'].reset_index()
avg_rating_df.rename(columns={'Book-Rating':'avg_rating'},inplace=True)
avg_rating_df

Book-Title  avg_rating
0        A Light in the Storm: The Civil War Diary of ...    2.250000
1                                   Always Have Popsicles    0.000000
2                    Apple Magic (The Collector's series)    0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...    8.000000
4        Beyond IBM: Leadership Marketing and Finance ...    0.000000
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.    0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.    5.250000
241068                                Ã?Â?sterlich leben.    7.000000
241069                              Ã?Â?stlich der Berge.    2.666667
241070                                  Ã?Â?thique en toc    4.000000

[241071 rows x 2 columns]

In [12]:
popular_df = num_rating_df.merge(avg_rating_df,on='Book-Title')
popular_df

Book-Title  num_ratings  \
0        A Light in the Storm: The Civil War Diary of ...            4   
1                                   Always Have Popsicles            1   
2                    Apple Magic (The Collector's series)            1   
3        Ask Lily (Young Women of Faith: Lily Series, ...            1   
4        Beyond IBM: Leadership Marketing and Finance ...            1   
...                                                   ...          ...   
241066                                      Ã?Â?lpiraten.            2   
241067                     Ã?Â?rger mit Produkt X. Roman.            4   
241068                                Ã?Â?sterlich leben.            1   
241069                              Ã?Â?stlich der Berge.            3   
241070                                  Ã?Â?thique en toc            2   

        avg_rating  
0         2.250000  
1         0.000000  
2         0.000000  
3         8.000000  
4         0.000000  
...            ...  
241066    0.000000  
241067    5.250000  
241068    7.000000  
241069    2.666667  
241070    4.000000  

[241071 rows x 3 columns]

In [13]:
popular_df_avg = popular_df[popular_df['num_ratings']>=250].sort_values('avg_rating',ascending=False).head(10)
popular_df_avg

Book-Title  num_ratings  \
80434   Harry Potter and the Prisoner of Azkaban (Book 3)          428   
80422        Harry Potter and the Goblet of Fire (Book 4)          387   
80441      Harry Potter and the Sorcerer's Stone (Book 1)          278   
80426   Harry Potter and the Order of the Phoenix (Boo...          347   
80414    Harry Potter and the Chamber of Secrets (Book 2)          556   
191612  The Hobbit : The Enchanting Prelude to The Lor...          281   
187377  The Fellowship of the Ring (The Lord of the Ri...          368   
80445   Harry Potter and the Sorcerer's Stone (Harry P...          575   
211384     The Two Towers (The Lord of the Rings, Part 2)          260   
219741                              To Kill a Mockingbird          510   

        avg_rating  
80434     5.852804  
80422     5.824289  
80441     5.737410  
80426     5.501441  
80414     5.183453  
191612    5.007117  
187377    4.948370  
80445     4.895652  
211384    4.880769  
219741    4.700000

In [14]:
popular_df_num = popular_df[popular_df['num_ratings']>=250].sort_values('num_ratings',ascending=False).head(10)
popular_df_num

Book-Title  num_ratings  \
234951                                      Wild Animus         2502   
196326                        The Lovely Bones: A Novel         1295   
183573                                The Da Vinci Code          898   
5303                                    A Painted House          838   
199237                       The Nanny Diaries: A Novel          828   
27922                             Bridget Jones's Diary          815   
206502                          The Secret Life of Bees          774   
52983   Divine Secrets of the Ya-Ya Sisterhood: A Novel          740   
204387              The Red Tent (Bestselling Backlist)          723   
14392                               Angels &amp; Demons          670   

        avg_rating  
234951    1.019584  
196326    4.468726  
183573    4.642539  
5303      3.231504  
199237    3.530193  
27922     3.527607  
206502    4.447028  
52983     3.437838  
204387    4.334716  
14392     3.708955

In [15]:
popular_df = popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Image-URL-M','num_ratings','avg_rating']]

In [16]:
popular_df

Book-Title  \
0        A Light in the Storm: The Civil War Diary of ...   
1                                   Always Have Popsicles   
2                    Apple Magic (The Collector's series)   
3        Ask Lily (Young Women of Faith: Lily Series, ...   
4        Beyond IBM: Leadership Marketing and Finance ...   
...                                                   ...   
270291                                      Ã?Â?lpiraten.   
270292                     Ã?Â?rger mit Produkt X. Roman.   
270293                                Ã?Â?sterlich leben.   
270294                              Ã?Â?stlich der Berge.   
270295                                  Ã?Â?thique en toc   

                      Book-Author  \
0                     Karen Hesse   
1                  Rebecca Harvin   
2                Martina Boudreau   
3                    Nancy N. Rue   
4                      Lou Mobley   
...                           ...   
270291  Janwillem van de Wetering   
270292                 Joan Aiken   
270293             Anselm Gr�¼n   
270294             David Guterson   
270295           Didier Daeninckx   

                                              Image-URL-M  num_ratings  \
0       http://images.amazon.com/images/P/0590567330.0...            4   
1       http://images.amazon.com/images/P/0964147726.0...            1   
2       http://images.amazon.com/images/P/0942320093.0...            1   
3       http://images.amazon.com/images/P/0310232546.0...            1   
4       http://images.amazon.com/images/P/0962295701.0...            1   
...                                                   ...          ...   
270291  http://images.amazon.com/images/P/3499232499.0...            2   
270292  http://images.amazon.com/images/P/325721538X.0...            4   
270293  http://images.amazon.com/images/P/3451274973.0...            1   
270294  http://images.amazon.com/images/P/3442725739.0...            3   
270295  http://images.amazon.com/images/P/2842192508.0...            2   

        avg_rating  
0         2.250000  
1         0.000000  
2         0.000000  
3         8.000000  
4         0.000000  
...            ...  
270291    0.000000  
270292    5.250000  
270293    7.000000  
270294    2.666667  
270295    4.000000  

[241071 rows x 5 columns]

In [ ]:
##CATEGORY BASED / CONTENT BASED METHOD##

In [17]:
x = ratings_with_name.groupby('User-ID').count()['Book-Rating'] > 200
read_users = x[x].index

In [18]:

filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(read_users)]

In [19]:
y = filtered_rating.groupby('Book-Title').count()['Book-Rating']>=50
famous_books = y[y].index

In [20]:
final_ratings = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [21]:
pt = final_ratings.pivot_table(index='Book-Title',columns='User-ID',values='Book-Rating')

In [22]:
pt.fillna(0,inplace=True)

In [23]:
pt

User-ID                                             254     2276    2766    \
Book-Title                                                                   
1984                                                   9.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0    10.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
A Bend in the Road                                     0.0     0.0     7.0   
...                                                    ...     ...     ...   
Year of Wonders                                        0.0     0.0     0.0   
You Belong To Me                                       0.0     0.0     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0     0.0     0.0   
Zoya                                                   0.0     0.0     0.0   
\O\" Is for Outlaw"                                    0.0     0.0     0.0   

User-ID                                             2977    3363    4017    \
Book-Title                                                                   
1984                                                   0.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0     0.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
A Bend in the Road                                     0.0     0.0     0.0   
...                                                    ...     ...     ...   
Year of Wonders                                        7.0     0.0     0.0   
You Belong To Me                                       0.0     0.0     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0     0.0     0.0   
Zoya                                                   0.0     0.0     0.0   
\O\" Is for Outlaw"                                    0.0     0.0     0.0   

User-ID                                             4385    6251    6323    \
Book-Title                                                                   
1984                                                   0.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0     0.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
A Bend in the Road                                     0.0     0.0     0.0   
...                                                    ...     ...     ...   
Year of Wonders                                        0.0     0.0     0.0   
You Belong To Me                                       0.0     0.0     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0     0.0     0.0   
Zoya                                                   0.0     0.0     0.0   
\O\" Is for Outlaw"                                    0.0     0.0     0.0   

User-ID                                             6543    ...  271705  \
Book-Title                                                  ...           
1984                                                   0.0  ...    10.0   
1st to Die: A Novel                                    9.0  ...     0.0   
2nd Chance                                             0.0  ...     0.0   
4 Blondes                                              0.0  ...     0.0   
A Bend in the Road                                     0.0  ...     0.0   
...                                                    ...  ...     ...   
Year of Wonders                                        0.0  ...     0.0   
You Belong To Me                                       0.0  ...     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0  ...     0.0   
Zoya                                                   0.0  ...     0.0   
\O\" Is for Outlaw"                                    

In [24]:
similarity_scores = cosine_similarity(pt)

In [25]:
similarity_scores.shape

(706, 706)

In [26]:
def recommend(book_name):
    # index fetch
    index = np.where(pt.index==book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_scores[index])),key=lambda x:x[1],reverse=True)[1:5]
    
    data = []
    for i in similar_items:
        item = []
        temp_df = books[books['Book-Title'] == pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))
        
        data.append(item)
    
    return data

In [27]:
recommend('1984')

[['Animal Farm',
  'George Orwell',
  'http://images.amazon.com/images/P/0451526341.01.MZZZZZZZ.jpg'],
 ["The Handmaid's Tale",
  'Margaret Atwood',
  'http://images.amazon.com/images/P/0449212602.01.MZZZZZZZ.jpg'],
 ['Brave New World',
  'Aldous Huxley',
  'http://images.amazon.com/images/P/0060809833.01.MZZZZZZZ.jpg'],
 ['The Vampire Lestat (Vampire Chronicles, Book II)',
  'ANNE RICE',
  'http://images.amazon.com/images/P/0345313860.01.MZZZZZZZ.jpg']]

In [28]:
##Collaborative Filtering Recommendor Model##

In [29]:
piv_t_similiar = final_ratings.pivot_table(index='User-ID',columns='Book-Title',values='Book-Rating')
piv_t_similiar.fillna(0,inplace=True)

piv_t_similiar

Book-Title  1984  1st to Die: A Novel  2nd Chance  4 Blondes  \
User-ID                                                        
254          9.0                  0.0         0.0        0.0   
2276         0.0                  0.0        10.0        0.0   
2766         0.0                  0.0         0.0        0.0   
2977         0.0                  0.0         0.0        0.0   
3363         0.0                  0.0         0.0        0.0   
...          ...                  ...         ...        ...   
274308       0.0                  0.0         0.0        0.0   
275970       0.0                  0.0         0.0        0.0   
277427       0.0                  0.0         0.0        0.0   
277639       0.0                  0.0         0.0        0.0   
278418       0.0                  0.0         0.0        0.0   

Book-Title  A Bend in the Road  A Case of Need  \
User-ID                                          
254                        0.0             0.0   
2276                       0.0             0.0   
2766                       7.0             0.0   
2977                       0.0             0.0   
3363                       0.0             0.0   
...                        ...             ...   
274308                     0.0             7.0   
275970                     0.0             0.0   
277427                     0.0             0.0   
277639                     0.0             0.0   
278418                     0.0             0.0   

Book-Title  A Child Called \It\": One Child's Courage to Survive"  \
User-ID                                                             
254                                                       0.0       
2276                                                      0.0       
2766                                                      0.0       
2977                                                      0.0       
3363                                                      0.0       
...                                                       ...       
274308                                                    0.0       
275970                                                    0.0       
277427                                                    0.0       
277639                                                    0.0       
278418                                                    0.0       

Book-Title  A Civil Action  A Day Late and a Dollar Short  A Fine Balance  \
User-ID                                                                     
254                    0.0                            0.0             0.0   
2276                   0.0                            0.0             0.0   
2766                   0.0                            0.0             0.0   
2977                   0.0                            0.0             0.0   
3363                   0.0                            0.0             0.0   
...                    ...                            ...             ...   
274308                 0.0                            0.0             0.0   
275970                 0.0                            0.0             0.0   
277427                 0.0                            0.0             0.0   
277639                 0.0                            0.0             0.0   
278418                 0.0                            0.0             0.0   

Book-Title  ...  Winter Solstice  Wish You Well  Without Remorse  \
User-ID     ...                                                    
254         ...              0.0            0.0              0.0   
2276        ...              0.0            0.0              0.0   
2766        ...              0.0            0.0              0.0   
2977        ...              0.0            0.0              0.0   
3363        ...              0.0            0.0              0.0   
...         ...              ...            ...              ...   
274308      ...              0.0            0.0              0.0   
2759

In [30]:
piv_t_similiar['user_index'] = np.arange(0, piv_t_similiar.shape[0])
piv_t_similiar.set_index(['user_index'], inplace=True)

# Actual ratings given by users
piv_t_similiar.head()

Book-Title  1984  1st to Die: A Novel  2nd Chance  4 Blondes  \
user_index                                                     
0            9.0                  0.0         0.0        0.0   
1            0.0                  0.0        10.0        0.0   
2            0.0                  0.0         0.0        0.0   
3            0.0                  0.0         0.0        0.0   
4            0.0                  0.0         0.0        0.0   

Book-Title  A Bend in the Road  A Case of Need  \
user_index                                       
0                          0.0             0.0   
1                          0.0             0.0   
2                          7.0             0.0   
3                          0.0             0.0   
4                          0.0             0.0   

Book-Title  A Child Called \It\": One Child's Courage to Survive"  \
user_index                                                          
0                                                         0.0       
1                                                         0.0       
2                                                         0.0       
3                                                         0.0       
4                                                         0.0       

Book-Title  A Civil Action  A Day Late and a Dollar Short  A Fine Balance  \
user_index                                                                  
0                      0.0                            0.0             0.0   
1                      0.0                            0.0             0.0   
2                      0.0                            0.0             0.0   
3                      0.0                            0.0             0.0   
4                      0.0                            0.0             0.0   

Book-Title  ...  Winter Solstice  Wish You Well  Without Remorse  \
user_index  ...                                                    
0           ...              0.0            0.0              0.0   
1           ...              0.0            0.0              0.0   
2           ...              0.0            0.0              0.0   
3           ...              0.0            0.0              0.0   
4           ...              0.0            0.0              0.0   

Book-Title  Wizard and Glass (The Dark Tower, Book 4)  Wuthering Heights  \
user_index                                                                 
0                                                 0.0                0.0   
1                                                 0.0                0.0   
2                                                 0.0                0.0   
3                                                 0.0                0.0   
4                                                 0.0                0.0   

Book-Title  Year of Wonders  You Belong To Me  \
user_index                                      
0                       0.0               0.0   
1                       0.0               0.0   
2                       0.0               0.0   
3                       7.0               0.0   
4                       0.0               0.0   

Book-Title  Zen and the Art of Motorcycle Maintenance: An Inquiry into Values  \
user_index                                                                      
0                                                         0.0                   
1                                                         0.0                   
2                                                         0.0                   
3                                                         0.0                   
4                                                         0.0                   

Book-Title  Zoya  \O\" Is for Outlaw"  
user_index                             
0            0.0                  0.0  
1            0.0                  0.0  
2            0.0                  0.0  
3            0.0                  0.0  
4            0

In [31]:
##Function to find Similar users and their similarity scores

In [32]:
# defining a function to get similar users
def similar_users(user_index, interactions_matrix):
    similarity = []
    for user in range(0, interactions_matrix.shape[0]): #  .shape[0] gives number of rows
        
        #finding cosine similarity between the user_id and each user
        sim = cosine_similarity([interactions_matrix.loc[user_index]], [interactions_matrix.loc[user]])
        
        #Appending the user and the corresponding similarity score with user_id as a tuple
        similarity.append((user,sim))
        
    similarity.sort(key=lambda x: x[1], reverse=True)
    most_similar_users = [tup[0] for tup in similarity] #Extract the user from each tuple in the sorted list
    similarity_score = [tup[1] for tup in similarity] ##Extracting the similarity score from each tuple in the sorted list
   
    #Remove the original user and its similarity score and keep only other similar users 
    most_similar_users.remove(user_index)
    similarity_score.remove(similarity_score[0])
       
    return most_similar_users, similarity_score

In [33]:
similar = similar_users(3,piv_t_similiar)[0][0:10]
similar

[99, 332, 240, 735, 578, 517, 383, 444, 181, 316]

In [34]:
#Print the similarity score
similar_users(3,piv_t_similiar)[1][0:10]

[array([[0.34757067]]),
 array([[0.33951597]]),
 array([[0.30383143]]),
 array([[0.25028596]]),
 array([[0.24064038]]),
 array([[0.23718779]]),
 array([[0.21863047]]),
 array([[0.21729042]]),
 array([[0.21167593]]),
 array([[0.20784167]])]

In [35]:
##Function to recommend products

In [36]:
# defining the recommendations function to get recommendations by using the similar users' preferences
def recommendations(user_index, num_of_products, interactions_matrix):
    
    #Saving similar users using the function similar_users defined above
    most_similar_users = similar_users(user_index, interactions_matrix)[0]
    
    #Finding product IDs with which the user_id has interacted
    prod_ids = set(list(interactions_matrix.columns[np.where(interactions_matrix.loc[user_index] > 0)]))
    recommendations = []
    
    observed_interactions = prod_ids.copy()
    for similar_user in most_similar_users:
        if len(recommendations) < num_of_products:
            
            #Finding 'n' products which have been rated by similar users but not by the user_id
            similar_user_prod_ids = set(list(interactions_matrix.columns[np.where(interactions_matrix.loc[similar_user] > 0)]))
            recommendations.extend(list(similar_user_prod_ids.difference(observed_interactions)))
            observed_interactions = observed_interactions.union(similar_user_prod_ids)
        else:
            break
    
    return recommendations[:num_of_products]

In [37]:
recommendations(3,5,piv_t_similiar)

['Wild Animus',
 'The Thorn Birds',
 'Lord of the Flies',
 'The Perfect Storm : A True Story of Men Against the Sea',
 'The Boy Next Door']

In [38]:
recommendations(124,5,piv_t_similiar)

['The Perfect Storm : A True Story of Men Against the Sea',
 'The Deep End of the Ocean',
 'Tis : A Memoir',
 'The Diary of Ellen Rimbauer: My Life at Rose Red',
 "Foucault's Pendulum"]

In [41]:
import pickle
pickle.dump(popular_df,open('popular.pkl','wb'))
pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(books,open('books.pkl','wb'))
pickle.dump(similarity_scores,open('similarity_scores.pkl','wb'))
pickle.dump(piv_t_similiar,open('booksByUser.pkl','wb'))

In [42]:
similarity_scores = cosine_similarity(piv_t_similiar)

In [44]:
similarity_scores.shape

(810, 810)

In [53]:
def recommend(user_index):
    #Saving similar users using the function similar_users defined above
    most_similar_users = similar_users(user_index, interactions_matrix)[0]
    
    #Finding product IDs with which the user_id has interacted
    prod_ids = set(list(interactions_matrix.columns[np.where(interactions_matrix.loc[user_index] > 0)]))
    recommendations = []
    
    observed_interactions = prod_ids.copy()
    for similar_user in most_similar_users:
        if len(recommendations) < num_of_products:
            
            #Finding 'n' products which have been rated by similar users but not by the user_id
            similar_user_prod_ids = set(list(interactions_matrix.columns[np.where(interactions_matrix.loc[similar_user] > 0)]))
            recommendations.extend(list(similar_user_prod_ids.difference(observed_interactions)))
            observed_interactions = observed_interactions.union(similar_user_prod_ids)
        else:
            break
    
    return recommendations[:num_of_products]

In [55]:
books

ISBN                                         Book-Title  \
0       0195153448                                Classical Mythology   
1       0002005018                                       Clara Callan   
2       0060973129                               Decision in Normandy   
3       0374157065  Flu: The Story of the Great Influenza Pandemic...   
4       0393045218                             The Mummies of Urumchi   
...            ...                                                ...   
271355  0440400988                         There's a Bat in Bunk Five   
271356  0525447644                            From One to One Hundred   
271357  006008667X  Lily Dale : The True Story of the Town that Ta...   
271358  0192126040                        Republic (World's Classics)   
271359  0767409752  A Guided Tour of Rene Descartes' Meditations o...   

                 Book-Author Year-Of-Publication  \
0         Mark P. O. Morford                2002   
1       Richard Bruce Wright                2001   
2               Carlo D'Este                1991   
3           Gina Bari Kolata                1999   
4            E. J. W. Barber                1999   
...                      ...                 ...   
271355        Paula Danziger                1988   
271356            Teri Sloat                1991   
271357      Christine Wicker                2004   
271358                 Plato                1996   
271359   Christopher  Biffle                2000   

                                               Publisher  \
0                                Oxford University Press   
1                                  HarperFlamingo Canada   
2                                        HarperPerennial   
3                                   Farrar Straus Giroux   
4                             W. W. Norton &amp; Company   
...                                                  ...   
271355                   Random House Childrens Pub (Mm)   
271356                                      Dutton Books   
271357                                HarperSanFrancisco   
271358                           Oxford University Press   
271359  McGraw-Hill Humanities/Social Sciences/Languages   

                                              Image-URL-S  \
0       http://images.amazon.com/images/P/0195153448.0...   
1       http://images.amazon.com/images/P/0002005018.0...   
2       http://images.amazon.com/images/P/0060973129.0...   
3       http://images.amazon.com/images/P/0374157065.0...   
4       http://images.amazon.com/images/P/0393045218.0...   
...                                                   ...   
271355  http://images.amazon.com/images/P/0440400988.0...   
271356  http://images.amazon.com/images/P/0525447644.0...   
271357  http://images.amazon.com/images/P/006008667X.0...   
271358  http://images.amazon.com/images/P/0192126040.0...   
271359  http://images.amazon.com/images/P/0767409752.0...   

                                              Image-URL-M  \
0       http://images.amazon.com/images/P/0195153448.0...   
1       http://images.amazon.com/images/P/0002005018.0...   
2       http://images.amazon.com/images/P/0060973129.0...   
3       http://images.amazon.com/images/P/0374157065.0...   
4       http://images.amazon.com/images/P/0393045218.0...   
...                                                   ...   
271355  http://images.amazon.com/images/P/0440400988.0...   
271356  http://images.amazon.com/images/P/0525447644.0...   
271357  http://images.amazon.com/images/P/006008667X.0...   
271358  http://images.amazon.com/images/P/0192126040.0...   
271359  http://images.amazon.com/images/P/0767409752.0...   

                                              Image-URL-L  
0       http://images.amazon.com/images/P/0195153448.0...  
1       http://images.amazon.com/images/P/0002005018.0...  
2       http://images.amazon.com/images/P/0060973129.0...  
3       http://images.amazon.com/images/P/0374157065.0...  
4       http://images.ama